name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        
      - name: Debug project structure
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Client directory content:"
          ls -la client || echo "No client directory found"

      - name: Create build directory
        run: mkdir -p build
        
      - name: Create 404.html for SPA routing
        run: |
          mkdir -p static-assets
          cat > static-assets/404.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Association Amal Ait Sadden</title>
            <script>
              // Capture the path and query params from the current URL
              const path = window.location.pathname.slice(1);
              const query = window.location.search.slice(1);
              
              // Redirect to the index.html with these params
              window.location.href = 
                window.location.origin + 
                window.location.pathname.split('/').slice(0, -1).join('/') + 
                '/' +
                '?' + 
                (path ? 'p=' + path + '&' : '') + 
                query;
            </script>
          </head>
          <body>
            <p>Redirecting to homepage...</p>
          </body>
          </html>
          EOL

      - name: Set up Tailwind CSS
        run: |
          if [ ! -f "client/vite.config.gh.js" ]; then
            echo "Creating a GitHub Pages specific Vite config in client directory..."
            cat > client/vite.config.gh.js << 'EOL'
          import { defineConfig } from "vite";
          import react from "@vitejs/plugin-react";
          import path from "path";

          // GitHub Pages specific configuration - simplified for build process
          export default defineConfig({
            plugins: [react()],
            resolve: {
              alias: {
                '@': path.resolve(__dirname, "src"),
                '@shared': path.resolve(__dirname, "../shared"),
                '@assets': path.resolve(__dirname, "../attached_assets"),
              },
            },
            build: {
              outDir: path.resolve(__dirname, "../build"),
              emptyOutDir: true,
              sourcemap: false,
              minify: true,
            },
            base: './',
          });
          EOL
          else
            echo "Using existing client/vite.config.gh.js"
          fi
          
      - name: Build the project
        run: |
          echo "Building the client-side React application..."
          # Direct approach with Vite using our client-specific config
          cd client && npx vite build --config vite.config.gh.js && cd ..
          
          # Verify build directory
          echo "Build directory content:"
          ls -la build || echo "No build directory found"
          
          # Copy 404.html to build directory
          cp static-assets/404.html build/404.html || echo "Failed to copy 404.html"
          
          # Add SPA routing handler to index.html if it exists
          if [ -f "build/index.html" ]; then
            # Create a backup of index.html
            cp build/index.html build/index.html.bak
            
            # Add the script using a temporary file
            awk '/<head>/ { print $0; print "  <script>\n    // Handle GitHub Pages routing\n    (function() {\n      const query = window.location.search.substring(1);\n      const pairs = query.split(\"&\").map(pair => pair.split(\"=\"));\n      const params = pairs.reduce((acc, pair) => {\n        acc[decodeURIComponent(pair[0])] = decodeURIComponent(pair[1] || \"\");\n        return acc;\n      }, {});\n      \n      if (params.p) {\n        history.replaceState(null, null, params.p + (query.replace(\"p=\" + params.p, \"\") ? \"?\" + query.replace(\"p=\" + params.p + \"&\", \"\").replace(\"p=\" + params.p, \"\") : \"\"));\n      }\n    })();\n  </script>"; next = 0 } { if (next == 0) print $0; next = 1 }' build/index.html.bak > build/index.html.tmp
            mv build/index.html.tmp build/index.html
          else
            echo "Warning: build/index.html not found"
          fi

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch the action should deploy to.
          folder: build  # The folder the action should deploy.
          clean: true  # Automatically remove deleted files from the deploy branch